name: 150BPM
favicon: null
layout_spectrum: 0.75522
typography_spectrum: 0.13743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfdfc'
    - '#e14419'
    - '#641a4f'
    - '#a9ca21'
    - '#000000'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
