analytics: {}
color:
  brandColors:
    - '#fbfdfc'
    - '#e14419'
    - '#641a4f'
    - '#a9ca21'
    - '#000000'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 1
name: 150BPM
opengraph: {}
purpose: []
typography_spectrum: 0.13743
